version: 1.0.{build}

image:
  - Visual Studio 2008
  - Visual Studio 2010
  - Visual Studio 2012
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x86
  - x64
  - ARM

configuration:
  - Release

environment:
  access_token:
    secure: A/4rfTb0Vd7FoAjKEBq/1u3QjwGegZQKXRm0RJqSQGtZaI28wO/k8AcBq3iWbvaA

clone_folder: C:\projects\c-genericlogger
clone_depth: 1 # Not needing of all the history - just the HEAD
shallow_clone: false

build_script:
  - cd C:\projects\c-genericlogger
  - cmake -G "NMake Makefiles" .
  - nmake

test_script:
  - cd C:\projects\c-genericlogger
  - nmake check
  - nmake install
  - nmake pack
