name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure
      run: cmake -S . -B ..\build_folder -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "NMake Makefiles"

    - name: Build
      run: cmake --build ..\build_folder

    - name: Test
      run: ctest --test-dir ..\build_folder

    - name: Install
      run: cmake --install ..\build_folder --prefix ..\install_folder

    - name: Package
      run: cmake --build ..\build_folder --target package
